Chore: Adding Black + Flake8 Linters
databrickslabs/tempo pull request #203
Opened 2022-05-10 20:08 UTC by guanjieshen

2022-05-10 21:46 UTC, guanjieshen commented
Some alerts from flake8 around unused variables:

```
./python/tests/tsdf_tests.py:194:9: F841 local variable 'dfRight' is assigned to but never used
./python/tests/tsdf_tests.py:195:9: F841 local variable 'dfExpected' is assigned to but never used
./python/tests/tsdf_tests.py:1214:9: F841 local variable 'expectedSchema' is assigned to but never used
./python/tests/tsdf_tests.py:1261:9: F841 local variable 'interpolated' is assigned to but never used
./python/tests/tsdf_tests.py:1388:9: F841 local variable 'dfExpected' is assigned to but never used
```

2022-05-11 00:05 UTC, tnixon commented
@guanjieshen looks like you need to resolve merge conflicts

2022-05-13 21:32 UTC, tnixon commented on .github/workflows/test.yml
>    run:
Now that we have multiple jobs in this workflow, let's give this one a more descriptive name than just "run". Maybe "test" and `name: Build and Test Module`

2022-05-13 21:40 UTC, tnixon requested changes
@guanjieshen - there seem to be a lot of changes that are just cosmetic formatting of code. It makes it hard to distinguish the important changes for this functionality from general code cleanup. Could you please submit just the necessary changes, and leave out any formatting. 

I'm not against code cleanup when it aids in readability, but those should be submitted as their own PR and not crammed into an unrelated change.

2022-05-13 21:42 UTC, tnixon commented
... or are these formatting changes in order to get Flake8 to pass?

2022-06-14 23:05 UTC, guanjieshen commented
@tnixon going to close this PR for now and start a new one to see if we can better layer in the linter changes rather than have it in a giant PR.

2022-06-14 23:05 UTC, closed without merging