Db2 license
databrickslabs/tempo pull request #325
Opened 2023-05-03 22:30 UTC by tnixon

Moving to new DB license so that we can accept external contributions.

2023-05-03 22:51 UTC, R7L208 commented on README.md
> +More comprehensive instructions on setting up and building the project can be found in [BUILDING.md](BUILDING.md) and [CONTRIBUTING.md](CONTRIBUTING.md).
Do we need this here and in `CONTRIBUTING.md`?

2023-05-03 22:53 UTC, R7L208 reviewed
If possible, let's add new contribution details in README.md or CONTRIBUTING.md but not both. Maybe in the README we can just state that we welcome contributions and details are in the CONTRIBUTING file?

2023-05-03 23:16 UTC, tnixon commented
Yes, that makes sense. Do you think we can consolidate Build.md into CONTRIBUTING.md? Just have a single place for all setup and build instructions.

2023-05-04 02:24 UTC, rportilla-databricks requested changes

2023-05-04 02:24 UTC, rportilla-databricks commented on CONTRIBUTING.md
> +## Tox Setup instructions
Shouldn't tox be in the README.md and documentation? I think pandas is a good example of placing build instructions in the official docs with BSD 3 license strictly having terms for contribution. Separately, building is up to the tempo project and should be in the github workflows (e.g. https://github.com/pandas-dev/pandas/blob/main/.github/workflows/wheels.yml)

2023-11-27 23:12 UTC, closed without merging